_filesCore = [
  'j3'
  'oo'
  'user-agent'
  'string-builder'
  'url-query'
  'date-time'
  'string'
  'template'
  'list'
  'compile'
  'enumerate'
  'pool'
  'event-manager'
  'datasource'
  'data-view'
  'model'
  'collection'
  'collection-view'
  'grouped-collection'
]
task 'build', 'build j3 libarary', (options) ->
  packflow = require 'packflow'
  packflow.pack require './pack-project'
